import React, { useState, useEffect } from "react";
import { motion } from "framer-motion";
import { ArrowRight, BookOpen, Zap, BarChart3, Users } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { apiClient } from "../services/apiClient";

export function HomePage() {
  const navigate = useNavigate();
  const [stats, setStats] = useState(null);
  const [loading, setLoading] = useState(true);

  // Default stats to show
  const defaultStats = {
    total_users: "50K+",
    total_questions: "10K+",
    total_topics: "60+",
    success_rate: "92%",
  };

  useEffect(() => {
    const fetchStats = async () => {
      try {
        setLoading(true);
        const data = await apiClient.getStats();
        setStats(data);
      } catch (err) {
        console.warn("⚠️ Stats endpoint not available, using defaults:", err.message);
        // Use default stats if endpoint fails
        setStats(defaultStats);
      } finally {
        setLoading(false);
      }
    };

    fetchStats();
  }, []);

  const features = [
    {
      icon: Zap,
      title: "AI-Powered Exams",
      description: "Get personalized exam questions generated by AI based on your level",
    },
    {
      icon: BarChart3,
      title: "Smart Analytics",
      description: "Track your progress with detailed performance metrics and insights",
    },
    {
      icon: BookOpen,
      title: "60+ Topics",
      description: "Master coding, system design, and technical interview concepts",
    },
    {
      icon: Users,
      title: "Compete & Learn",
      description: "Compare your skills with others on our global leaderboard",
    },
  ];

  const statVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: (i) => ({
      opacity: 1,
      y: 0,
      transition: { delay: i * 0.1, duration: 0.5 },
    }),
  };

  return (
    <div className="min-h-screen bg-gradient-to-b from-blue-50 to-white dark:from-slate-950 dark:to-slate-900">
      {/* Hero Section */}
      <motion.div
        className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 pt-20 pb-16 text-center"
        initial={{ opacity: 0, y: 30 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
      >
        <h1 className="text-5xl sm:text-6xl font-bold text-gray-900 dark:text-white mb-6">
          Master Technical Interviews
        </h1>
        <p className="text-xl text-gray-600 dark:text-gray-300 mb-8 max-w-2xl mx-auto">
          ExamForge helps you prepare for technical interviews with AI-generated questions,
          detailed explanations, and performance tracking.
        </p>

        <motion.button
          whileHover={{ scale: 1.05 }}
          whileTap={{ scale: 0.95 }}
          onClick={() => navigate("/exam/setup")}
          className="bg-gradient-to-r from-blue-600 to-purple-600 text-white px-8 py-4 rounded-lg font-bold text-lg inline-flex items-center gap-2 hover:shadow-lg transition-all"
        >
          Start Your First Exam <ArrowRight className="w-5 h-5" />
        </motion.button>
      </motion.div>

      {/* Stats */}
      <motion.div
        className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-12 grid grid-cols-2 md:grid-cols-4 gap-4 mb-20"
        initial="hidden"
        animate="visible"
      >
        {[
          { label: "Users", value: stats?.total_users || "50K+" },
          { label: "Questions", value: stats?.total_questions || "10K+" },
          { label: "Topics", value: stats?.total_topics || "60+" },
          { label: "Success Rate", value: stats?.success_rate || "92%" },
        ].map((stat, i) => (
          <motion.div
            key={i}
            custom={i}
            variants={statVariants}
            className="bg-white dark:bg-gray-800 rounded-lg p-6 text-center shadow-sm"
          >
            <p className="text-3xl font-bold text-blue-600 dark:text-blue-400 mb-2">
              {stat.value}
            </p>
            <p className="text-gray-600 dark:text-gray-400 text-sm">{stat.label}</p>
          </motion.div>
        ))}
      </motion.div>

      {/* Features */}
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 pb-20">
        <h2 className="text-4xl font-bold text-gray-900 dark:text-white mb-12 text-center">
          Why Choose ExamForge?
        </h2>

        <motion.div
          className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6"
          initial="hidden"
          animate="visible"
          variants={{
            hidden: { opacity: 0 },
            visible: {
              opacity: 1,
              transition: { staggerChildren: 0.1 },
            },
          }}
        >
          {features.map((feature, idx) => {
            const Icon = feature.icon;
            return (
              <motion.div
                key={idx}
                className="bg-white dark:bg-gray-800 rounded-lg p-6 shadow-sm hover:shadow-lg transition-all"
                whileHover={{ y: -5 }}
                variants={statVariants}
                custom={idx}
              >
                <Icon className="w-12 h-12 text-blue-600 dark:text-blue-400 mb-4" />
                <h3 className="font-bold text-gray-900 dark:text-white mb-2">{feature.title}</h3>
                <p className="text-gray-600 dark:text-gray-400 text-sm">
                  {feature.description}
                </p>
              </motion.div>
            );
          })}
        </motion.div>
      </div>

      {/* CTA Section */}
      <div className="bg-gradient-to-r from-blue-600 to-purple-600 py-16">
        <motion.div
          className="max-w-4xl mx-auto px-4 text-center text-white"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3 }}
        >
          <h2 className="text-4xl font-bold mb-4">Ready to get started?</h2>
          <p className="text-lg mb-8 opacity-90">
            Choose your skill level and topics to begin your journey
          </p>
          <motion.button
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            onClick={() => window.location.href = "/exam-setup"}
            className="bg-white text-blue-600 px-8 py-3 rounded-lg font-bold hover:bg-gray-100 transition-all"
          >
            Start Exam Setup
          </motion.button>
        </motion.div>
      </div>
    </div>
  );
}
